version: '3.1'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    expose:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100
    expose:
      - 9100

  loki:
    image: grafana/loki:2.7.3
    restart: unless-stopped
    volumes:
      - loki:/loki
    expose:
      - 3100
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.7.3
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

volumes:
  prometheus:
  loki:
