version: '3.1'

services:
  db_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  fastapi_example:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db_postgres
    volumes:
      - type: bind
        source: ./
        target: /app

  nginx-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8800:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
